from curl_cffi import requests                                                                                                                                                                                                                                                                                                                                                                                                                       
from typing import Union, List                                                                                                                                                                                                                                                                                                                                                                                                                       
from util import Util                                                                                                                                                                                                                                                                                                                                                                                                                       

class Session:                                                                                                                                                                                                                                                                                                                                                                                                                       
    @staticmethod                                                                                                                                                                                                                                                                                                                                                                                                                       
    def session() -> List[Union[requests.Session, str, str, str]]:                                                                                                                                                                                                                                                                                                                                                                                                                       
        proxy = Util.get_random_proxy()                                                                                                                                                                                                                                                                                                                                                                                                                       

        browsers = [                                                                                                                                                                                                                                                                                                                                                                                                                       
            ("chrome_133", '"Chromium";v="140", "Not=A?Brand";v="24", "Google Chrome";v="140"', "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36")                                                                                                                                                                                                                                                                                                                                                                                                                       
        ]                                                                                                                                                                                                                                                                                                                                                                                                                       

        impersonate, sec_ch_ua, user_agent = browsers[0]                                                                                                                                                                                                                                                                                                                                                                                                                       

        session = requests.Session(ja3="771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,5-11-43-16-45-35-18-27-65037-10-65281-23-51-13-17613-0,4588-29-23-24,0", proxies={"http": proxy, "https": proxy}, default_headers=0)                                                                                                                                                                                                                                                                                                                                                                                                                       

        return (session, sec_ch_ua, user_agent, proxy)                                                                                                                                                                                                                                                                                                                                                                                                                       